# Generated by Django 6.0.6 on 2026-06-13 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('model_name', models.CharField(help_text='e.g. Lead, LoanApplication', max_length=50)),
                ('trigger_type', models.CharField(choices=[('ON_CREATE', 'On Creation'), ('ON_UPDATE', 'On Update'), ('ON_STATUS_CHANGE', 'On Status Change')], max_length=50)),
                ('condition_field', models.CharField(blank=True, help_text='e.g. status', max_length=50, null=True)),
                ('condition_value', models.CharField(blank=True, help_text='e.g. APPROVED', max_length=50, null=True)),
                ('action_type', models.CharField(choices=[('SEND_EMAIL', 'Send Email'), ('SEND_SMS', 'Send SMS'), ('CHECK_CREDIT', 'Check Credit Score')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
