# Generated by Django 6.0.6 on 2026-06-13 07:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_type', models.CharField(choices=[('PERSONAL', 'Personal Loan'), ('HOME', 'Home Loan'), ('LAP', 'LAP'), ('BUSINESS', 'Business Loan'), ('EDUCATION', 'Education Loan'), ('CAR', 'Car Loan')], max_length=50)),
                ('requested_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tenure_months', models.IntegerField()),
                ('status', models.CharField(choices=[('PROCESSING', 'Processing'), ('VERIFICATION', 'Verification'), ('APPROVED', 'Approved'), ('SANCTIONED', 'Sanctioned'), ('DISBURSED', 'Disbursed'), ('REJECTED', 'Rejected')], default='PROCESSING', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='customers.customer')),
            ],
        ),
    ]
