# Generated by Django 6.0.6 on 2026-06-13 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='application_id',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
