# Generated by Django 6.0.6 on 2026-06-13 07:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('mobile', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('loan_type', models.CharField(choices=[('PERSONAL', 'Personal Loan'), ('HOME', 'Home Loan'), ('LAP', 'LAP'), ('BUSINESS', 'Business Loan'), ('EDUCATION', 'Education Loan'), ('CAR', 'Car Loan')], max_length=50)),
                ('source', models.CharField(choices=[('WEBSITE', 'Website'), ('FACEBOOK', 'Facebook'), ('GOOGLE_ADS', 'Google Ads'), ('WHATSAPP', 'WhatsApp'), ('REFERRAL', 'Referral'), ('MANUAL', 'Manual Entry')], default='MANUAL', max_length=50)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('CONTACTED', 'Contacted'), ('INTERESTED', 'Interested'), ('DOCUMENTS_PENDING', 'Documents Pending'), ('APPLIED', 'Applied'), ('PROCESSING', 'Processing'), ('VERIFICATION', 'Verification'), ('APPROVED', 'Approved'), ('SANCTIONED', 'Sanctioned'), ('DISBURSED', 'Disbursed'), ('REJECTED', 'Rejected')], default='NEW', max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_executive', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
