# Generated by Django 6.0.6 on 2026-06-13 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_otpverification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('ADMIN', 'Admin'), ('MANAGER', 'Manager'), ('LOAN_EXECUTIVE', 'Loan Executive'), ('TELECALLER', 'Telecaller'), ('OPERATIONS_EXECUTIVE', 'Operations Executive'), ('SUPPORT', 'Support Team')], default='LOAN_EXECUTIVE', max_length=50),
        ),
    ]
