name: Build and Push Docker Images

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME_BACKEND: ghcr.io/${{ github.repository_owner }}/instacapital-backend
  IMAGE_NAME_FRONTEND: ghcr.io/${{ github.repository_owner }}/instacapital-frontend

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Backend Image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile.prod
          push: true
          tags: ${{ env.IMAGE_NAME_BACKEND }}:latest,${{ env.IMAGE_NAME_BACKEND }}:${{ github.sha }}

      - name: Build and push Frontend Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./nginx/Dockerfile
          push: true
          tags: ${{ env.IMAGE_NAME_FRONTEND }}:latest,${{ env.IMAGE_NAME_FRONTEND }}:${{ github.sha }}
